github:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/*'

migrations:
  - changed-files:
      - any-glob-to-any-file: 'migrations/**/*'

my-root:
  - changed-files:
      - any-glob-to-any-file: '**/*'

go:
  - changed-files:
      - any-glob-to-any-file: '**/*'

csharp:
  - changed-files:
      - any-glob-to-any-file: '**/*'