github:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

actions:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/*'

migrations:
  - changed-files:
      - any-glob-to-any-file: 'migrations/**/*'
