name: "File Changes Labeler"

on:
- pull_request_target

jobs:
  file-changes-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler_templates.yml
        sync-labels: true