name: PR Checklist

on:
  pull_request_target:
    types: [opened]
    branches: [main]

jobs:
  checklist:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create checklist comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          tag: pr-checklist
          body: |
            ✅ Прежде чем мержить:
            - [ ] Проверить код
            - [ ] Запустить тесты
            - [ ] Обновить документацию
          edit-mode: replace